on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build game
    steps:
    # - name: Setup environment
    #   run: |
        # wget https://downloads.tuxfamily.org/godotengine/3.1.1/Godot_v3.1.1-stable_export_templates.tpz

        # mkdir ~/.cache
        # mkdir -p ~/.config/godot
        # mkdir -p ~/.local/share/godot/templates/3.1.1.stable
        # unzip Godot_v3.1.1-stable_export_templates.tpz
        # mv templates/* ~/.local/share/godot/templates/3.1.1.stable
        # rm -f Godot_v3.1.1-stable_export_templates.tpz
    - name: just run
      uses: aBARICHELLO/godot-ci
      run: |
        # Export for linux
        mkdir -p ./build/linux
        godot --export Linux/X11 ./build/linux/dark-forest

        # Export for Windows
        mkdir -p ./build/windows
        godot --export "Windows Desktop" ./build/windows/dark-forest.exe

        # Export for OSX
        mkdir -p ./builds/mac
        godot --export "Mac OSX" ./build/mac/dark-forest